"""Stage 3 - check the pulled data before anything is estimated on it.

The checks are in three groups.

*Completeness*: every quarter present, no gaps, no quarter with a suspicious
collapse in volume.

*Internal consistency*: no duplicate rows at the stated grain, no negative
passengers, no fares outside the filter that was supposed to have removed them,
no market whose carrier shares fail to sum to one.

*External agreement*: the series should look like the US airline industry. Total
passengers should fall in 2008-09 and rise through the 2010s. And the carriers
that were acquired should disappear from the ticketing data after their
mergers - Northwest after 2009, Continental after 2011, AirTran after 2014, US
Airways after 2015, Virgin America after 2018. That last check is the useful
one: it confirms the event dates the whole design rests on from the data itself
rather than from a table typed in by hand.

Writes reports/data_quality.md and exits non-zero if a hard check fails.
"""
from __future__ import annotations

import sys
from pathlib import Path

import duckdb
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import config as C

HARD_FAILURES: list[str] = []
WARNINGS: list[str] = []


def hard(ok: bool, msg: str) -> str:
    if not ok:
        HARD_FAILURES.append(msg)
    return "pass" if ok else "**FAIL**"


def soft(ok: bool, msg: str) -> str:
    if not ok:
        WARNINGS.append(msg)
    return "pass" if ok else "warn"


def main() -> int:
    con = duckdb.connect()
    con.execute("PRAGMA disable_progress_bar")
    glob = (C.DATA_RAW / "city_*.parquet").as_posix()
    con.execute(f"CREATE VIEW city AS SELECT * FROM read_parquet('{glob}')")

    lines = ["# Data quality report", "",
             "Generated by `src/03_validate.py`. Every number below is computed "
             "from the pulled files, not copied from the source documentation.", ""]

    # ---------------------------------------------------------- completeness
    q = con.execute("""
        SELECT year, quarter, SUM(pax) AS pax, COUNT(*) AS rows,
               COUNT(DISTINCT carrier) AS carriers
        FROM city GROUP BY 1,2 ORDER BY 1,2
    """).df()
    expected = C.quarters()
    got = list(zip(q["year"].astype(int), q["quarter"].astype(int)))
    lines += ["## Completeness", "",
              f"| check | value | result |", "|---|---|---|",
              f"| quarters expected | {len(expected)} | |",
              f"| quarters present | {len(got)} | "
              f"{hard(len(got) == len(expected), 'missing quarters')} |",
              f"| quarters in order with no gap | {got == expected} | "
              f"{hard(got == expected, 'quarter sequence has a gap')} |",
              f"| total sampled passengers | {q['pax'].sum():,.0f} | |",
              f"| total carrier-market-quarter rows | {q['rows'].sum():,.0f} | |", ""]

    # A quarter that lost half its volume relative to its neighbours is a
    # truncated download, not a real event.
    med = q["pax"].median()
    thin = q[q["pax"] < 0.5 * med]
    lines += [f"| quarters below half the median volume | {len(thin)} | "
              f"{hard(len(thin) == 0, 'a quarter looks truncated')} |", ""]

    # ------------------------------------------------- internal consistency
    dup = con.execute("""
        SELECT COUNT(*) FROM (
            SELECT year, quarter, city1, city2, carrier, COUNT(*) n
            FROM city GROUP BY 1,2,3,4,5 HAVING n > 1)
    """).fetchone()[0]
    neg = con.execute("SELECT COUNT(*) FROM city WHERE pax <= 0").fetchone()[0]
    badfare = con.execute(f"""
        SELECT COUNT(*) FROM city
        WHERE fare_pax / NULLIF(pax,0) < {C.MIN_FARE_NOMINAL}
           OR fare_pax / NULLIF(pax,0) > {C.MAX_FARE_NOMINAL}
    """).fetchone()[0]
    selfpair = con.execute("SELECT COUNT(*) FROM city WHERE city1 = city2").fetchone()[0]
    ordered = con.execute("SELECT COUNT(*) FROM city WHERE city1 > city2").fetchone()[0]

    lines += ["## Internal consistency", "",
              "| check | count | result |", "|---|---|---|",
              f"| duplicate rows at (quarter, market, carrier) | {dup:,} | "
              f"{hard(dup == 0, 'duplicate rows at the stated grain')} |",
              f"| rows with non-positive passengers | {neg:,} | "
              f"{hard(neg == 0, 'non-positive passenger counts')} |",
              f"| rows whose average fare escaped the filter | {badfare:,} | "
              f"{soft(badfare == 0, 'average fare outside the filter bounds')} |",
              f"| self-pairs (origin city = destination city) | {selfpair:,} | "
              f"{hard(selfpair == 0, 'self-pairs present')} |",
              f"| pairs not stored in canonical order | {ordered:,} | "
              f"{hard(ordered == 0, 'city pair not canonicalised')} |", ""]

    # --------------------------------------------------- external agreement
    lines += ["## Does it look like the airline industry?", "",
              "Sampled passengers by year, and the share of the busiest carrier.", "",
              "| year | sampled passengers | markets | carriers |", "|---|---|---|---|"]
    yr = con.execute("""
        SELECT year, SUM(pax) pax, COUNT(DISTINCT (city1, city2)) mkts,
               COUNT(DISTINCT carrier) carr
        FROM city GROUP BY 1 ORDER BY 1
    """).df()
    for _, r in yr.iterrows():
        lines.append(f"| {int(r['year'])} | {r['pax']:,.0f} | {int(r['mkts']):,} "
                     f"| {int(r['carr'])} |")
    rec = yr.set_index("year")["pax"]
    fell = rec.get(2009, 0) < rec.get(2007, 0)
    grew = rec.get(2019, 0) > rec.get(2009, 0)
    lines += ["",
              f"- Traffic fell from 2007 to 2009: **{fell}** "
              f"({soft(fell, 'no recession dip in traffic')})",
              f"- Traffic grew from 2009 to 2019: **{grew}** "
              f"({soft(grew, 'no recovery in traffic')})", ""]

    # ------------------------------------------- merger timing, from the data
    lines += ["## Merger timing, confirmed from the ticketing data", "",
              "The acquired carrier should stop appearing as a ticketing "
              "carrier once its brand is retired. The last quarter each one is "
              "seen with a meaningful passenger count is below, against the "
              "brand retirement date in `config.py`. This is the check that "
              "confirms the event dates the whole design rests on, from the "
              "data rather than from a table typed in by hand.", "",
              "| merger | acquired carrier | last quarter above 0.1% of its peak "
              "| brand retired | agrees |", "|---|---|---|---|---|"]
    for m in C.MERGERS:
        d = con.execute(f"""
            SELECT year, quarter, SUM(pax) pax FROM city
            WHERE carrier = '{m.target}' GROUP BY 1,2 ORDER BY 1,2
        """).df()
        if d.empty:
            lines.append(f"| {m.label} | {m.target} | never seen | | "
                         f"{hard(False, f'{m.target} absent from the data')} |")
            continue
        peak = d["pax"].max()
        alive = d[d["pax"] > 0.001 * peak]
        last = (int(alive["year"].iloc[-1]), int(alive["quarter"].iloc[-1]))
        cert = m.brand_retired
        # Allow a year of slack: passengers keep flying on the old code for a
        # while after the certificates merge.
        agree = abs(C.qindex(*last) - C.qindex(*cert)) <= 4
        lines.append(f"| {m.label} | {m.target} | {last[0]}Q{last[1]} | "
                     f"{cert[0]}Q{cert[1]} | "
                     f"{soft(agree, f'{m.target} exit does not match its brand retirement date')} |")
    lines.append("")

    # ------------------------------------------------------------- coverage
    cov = con.execute("""
        WITH mk AS (
            SELECT year, quarter, city1, city2, SUM(pax) pax
            FROM city GROUP BY 1,2,3,4)
        SELECT
            COUNT(*) AS market_quarters,
            SUM(CASE WHEN pax >= {} THEN 1 ELSE 0 END) AS above_threshold,
            SUM(CASE WHEN pax >= {} THEN pax ELSE 0 END) / SUM(pax) AS pax_share
        FROM mk
    """.format(C.MIN_MARKET_PAX_PER_Q, C.MIN_MARKET_PAX_PER_Q)).df().iloc[0]
    lines += ["## What the size filter keeps", "",
              f"Markets must carry at least {C.MIN_MARKET_PAX_PER_Q} sampled "
              f"passengers in a quarter, which is {C.MIN_MARKET_PAX_PER_Q/C.DB1B_SAMPLE_RATE:,.0f} "
              "real passengers.", "",
              f"| market-quarters before the filter | {cov['market_quarters']:,.0f} |",
              "|---|---|",
              f"| market-quarters kept | {cov['above_threshold']:,.0f} |",
              f"| share of all passengers kept | {cov['pax_share']:.1%} |", ""]
    lines.append(f"- The filter drops "
                 f"{1 - cov['above_threshold']/cov['market_quarters']:.0%} of "
                 f"market-quarters but only {1 - cov['pax_share']:.1%} of passengers: "
                 "the discarded markets are the very thin ones.")
    lines.append("")

    # ------------------------------------------------------------- verdict
    lines += ["## Verdict", ""]
    if HARD_FAILURES:
        lines.append("**Hard checks failed.** The pipeline should not be run on "
                     "this data until these are resolved.")
        lines += [f"- {m}" for m in HARD_FAILURES]
    else:
        lines.append("All hard checks pass.")
    if WARNINGS:
        lines += ["", "Warnings, which do not stop the pipeline:"]
        lines += [f"- {m}" for m in WARNINGS]
    lines.append("")

    C.REPORTS.mkdir(parents=True, exist_ok=True)
    out = C.REPORTS / "data_quality.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines[-14:]))
    print(f"\nwritten: {out}")
    return 1 if HARD_FAILURES else 0


if __name__ == "__main__":
    raise SystemExit(main())
